language: node_js
node_js:
  - "node"
script:
  - npm test
  - npm run build
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 
  app: building-buddies
  skip_cleanup: true
