language: node_js
node_js:
- stable
script:
- npm test
- npm run build
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: bDp9bfD0sybqdheQftb3UfxxkONPYlydrPYeWQSnvEJSpOAnZ3tVqLDxunjuSQUaVGoTDs8bQy4Pl32h1WjYw5Pzj7GAJgmpnsVpNklzT+vijh1JG1vDeLtOLV02t0Z9L/jOA/GxHr3MvhGIVzJdIaF7Y2+5mrpglOAeFXWcXjvak4NVp5sv/M4bCUeEWxRh5d53JVYUA+EcZ25gx5OGmSXCInE/nBNaXqPx/Cwq2m1OIi0umR4QI7rn0eH8bI29gOFHHJUs4Bs1g+SObQKku9ZB8LG1eLrt27lcXXkIk9A3Zi1ydZrTqcC2+wFge6sQcmKld5wzrcqdcpQ/ZHIsvV8flC3bLqolJqOlfugqKAvuKyWeUe0qSe64RKottDRZ+GHyunZhJQpFapOS6AJpJc2XsJPfTPv5HqNwMTl4P0s85UGFfQTkkoeECYWM1+vc2pRYciysfX11XvIsNB4hDRw+DGy1QX0jidf7fXUWG8g0aGvidQ3G4ihukUc+GhZMra0KgyIxLSHU0YPC7245jhYkkAB0i+4BuG0/uakToPE+OTDPih83BFMvAyLg+jN0RcHK4keTdCD1y8YcGU1wvO6VsipJuOTiWOKo1f/9OCwIyhUlif4K/4SkCAuoHcdmlUwZbxPDVBGyEYZZKjmsdspF97w8p2csv4FsyIG3R5Y=
  app: building-buddies
  skip_cleanup: true
